# Generated by Django 5.1.5 on 2025-01-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_colaborador_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='foto',
        ),
    ]
