# Generated by Django 5.1.5 on 2025-01-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_computadores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Computadores',
            new_name='Computador',
        ),
    ]
