# Generated by Django 5.1.5 on 2025-01-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_computadores_computador'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='foto',
            field=models.FileField(default='', upload_to='img'),
        ),
    ]
