# Generated by Django 5.1.5 on 2025-01-22 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_celular_responsavel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celular',
            name='modelo',
        ),
        migrations.AlterField(
            model_name='celular',
            name='responsavel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.colaborador'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='responsavel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.colaborador'),
        ),
    ]
