# Generated by Django 5.1.5 on 2025-01-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_celular_modelo_alter_celular_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='modelo',
            field=models.CharField(default=34, max_length=255),
            preserve_default=False,
        ),
    ]
