# Generated by Django 5.1.5 on 2025-01-22 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_celular_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.colaborador'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.colaborador'),
        ),
    ]
