# Generated by Django 5.1.5 on 2025-01-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_celular_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computador',
            name='processador',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computador',
            name='quantidade_memoria',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
