# Generated by Django 5.1.5 on 2025-01-22 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_computador_processador_computador_quantidade_memoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='foto',
        ),
        migrations.AlterField(
            model_name='celular',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celulares', to='home.colaborador'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computadores', to='home.colaborador'),
        ),
    ]
